name: Use JSON Output as Separate Environment Variables

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      jsonOutput: ${{ steps.generate_json.outputs.jsonData }}
    steps:
      - name: Generate JSON output
        id: generate_json
        run: |
          echo "::set-output name=jsonData::{\"key1\":\"value1\",\"key2\":\"value2\"}"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    env:
      KEY1: ${{ fromJson(needs.job1.outputs.jsonOutput).key1 }}
      KEY2: ${{ fromJson(needs.job1.outputs.jsonOutput).key2 }}
    steps:
      - name: Use the JSON keys as separate environment variables
        run: |
          echo "KEY1 is $KEY1"
          echo "KEY2 is $KEY2"
